### PR TITLE
Enable `pam_password`-like behavior, plus some other fixes

### PR DESCRIPTION
**Pull request by alanking**
Addresses #13
Addresses #23 
Addresses #29 
Addresses #30

### CODE REVIEW

**Comment by alanking** [comment]
The last commit in the bunch may or may not address #13. Feels like there's more stuff to be documented, but maybe this is just it.

**Comment by trel** [comment]
looks good - agreed about #13... please add it to the commit message for now... and we'll hold on deciding whether to close it later.

**Review by korydraughn — COMMENTED** [review]
Changes look good to me.

Have we seen success? Is this ready for pounds?

**Comment by alanking** [comment]
My version of success is seeing this build and I am able to authenticate with it using the pam_unix stack :) So... yes, I think it is ready. I added #13 to the commit title as mentioned.

**Comment by alanking** [comment]
Actually, there is some configuration for this plugin, but I would consider it in flux right now. Will report back here once it has been discussed.

**Comment by alanking** [comment]
After some discussion at the auth working group today as well as some additional investigation, we have determined that the configuration supported by this plugin is being used exclusively for the TTL parameter on the limited password used for authentication with iRODS. Therefore, we can probably remove it in favor of the `R_GRID_CONFIGURATION` values. I created https://github.com/irods/irods_auth_plugin_pam_interactive/issues/33 to address this. With all that being said, I don't think we need to include the existing configurations in the documentation. So, this change addresses #13 completely.

**Comment by korydraughn** [comment]
What's left for this?

**Review by korydraughn — APPROVED** [review]
If you're happy with it, pound it.

**Comment by alanking** [comment]
#'d. Mergin.

**Pull request merged**
