### PR TITLE
[#56] Only include postinst script in server package

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #56

Not tested yet, but I don't expect any surprises, so feel free to review.

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look good.

Awaiting results of testing.

**Review by alanking — COMMENTED** [review]
Yep, makes sense to me.

**Comment by SwooshyCueb** [comment]
Forgot to comment earlier, did some testing and everything seems to work as expected. If there are no objections, I will \#.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
